import { useEffect, useState } from 'react';
import api from '../lib/api.js';
import { BarChart3, Download, Plus, AlertCircle } from 'lucide-react';
import { format } from 'date-fns';
import { useForm } from 'react-hook-form';

const REPORT_TYPES = [
  { value: 'association_scorecard', label: 'Association Scorecard' },
  { value: 'round_summary', label: 'Round Summary Report' },
  { value: 'state_comparison', label: 'State Comparison Report' },
  { value: 'action_plan_progress', label: 'Action Plan Progress Report' },
];

export default function ReportsPage() {
  const [reports, setReports] = useState([]);
  const [showForm, setShowForm] = useState(false);
  const [formError, setFormError] = useState('');
  const [associations, setAssociations] = useState([]);
  const { register, handleSubmit, reset, formState: { isSubmitting } } = useForm();

  const fetchReports = () => api.get('/reports').then(r => setReports(r.data.data));

  useEffect(() => {
    fetchReports();
    api.get('/associations', { params: { limit: 100 } }).then(r => setAssociations(r.data.data));
  }, []);

  const onSubmit = async (data) => {
    setFormError('');
    try {
      await api.post('/reports/generate', data);
      reset();
      setShowForm(false);
      fetchReports();
    } catch (err) {
      setFormError(err.response?.data?.message || 'Failed to generate report. Please try again.');
    }
  };

  const handleDownload = async (report) => {
    try {
      const res = await api.get(`/reports/${report.id}/download`);
      // If a file URL is returned, open it
      if (res.data?.data?.fileUrl) {
        window.open(res.data.data.fileUrl, '_blank');
      } else {
        alert('Report file is not yet available. Generation may still be in progress.');
      }
    } catch (err) {
      alert(err.response?.data?.message || 'Download failed.');
    }
  };

  return (
    <div className="p-6 space-y-5">
      <div className="flex items-center justify-between">
        <h1 className="text-2xl font-bold text-gray-900">Reports</h1>
        <button className="btn-primary flex items-center gap-2" onClick={() => { setShowForm(true); setFormError(''); }}>
          <Plus size={16} /> Generate Report
        </button>
      </div>

      {showForm && (
        <div className="card p-5">
          <h2 className="font-semibold text-gray-900 mb-4">Generate New Report</h2>

          {formError && (
            <div className="bg-red-50 border border-red-200 text-red-700 px-4 py-3 rounded-xl text-sm flex items-start gap-2 mb-4">
              <AlertCircle size={15} className="shrink-0 mt-0.5" /> {formError}
            </div>
          )}

          <form onSubmit={handleSubmit(onSubmit)} className="grid grid-cols-2 gap-4">
            <div>
              <label className="label">Report Type *</label>
              <select className="input" {...register('reportType', { required: true })}>
                <option value="">Select type...</option>
                {REPORT_TYPES.map(t => <option key={t.value} value={t.value}>{t.label}</option>)}
              </select>
            </div>
            <div>
              <label className="label">Association (optional)</label>
              <select className="input" {...register('associationId')}>
                <option value="">All associations</option>
                {associations.map(a => <option key={a.id} value={a.id}>{a.name}</option>)}
              </select>
            </div>
            <div className="col-span-2 flex gap-3 justify-end">
              <button type="button" className="btn-secondary" onClick={() => { setShowForm(false); reset(); setFormError(''); }}>Cancel</button>
              <button type="submit" className="btn-primary" disabled={isSubmitting}>
                {isSubmitting ? 'Generating...' : 'Generate'}
              </button>
            </div>
          </form>
        </div>
      )}

      <div className="card overflow-hidden">
        <table className="w-full text-sm">
          <thead className="bg-gray-50 border-b border-gray-200">
            <tr>
              {['Report Type', 'Association', 'Generated By', 'Date', ''].map(h => (
                <th key={h} className="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wide">{h}</th>
              ))}
            </tr>
          </thead>
          <tbody className="divide-y divide-gray-100">
            {reports.length === 0 ? (
              <tr><td colSpan={5} className="px-4 py-12 text-center text-gray-400">
                <BarChart3 size={32} className="mx-auto mb-2 opacity-30" />
                No reports generated yet
              </td></tr>
            ) : reports.map(r => (
              <tr key={r.id} className="hover:bg-gray-50 transition-colors">
                <td className="px-4 py-3 font-medium capitalize">{r.reportType?.replace(/_/g, ' ')}</td>
                <td className="px-4 py-3 text-gray-500">{r.association?.name || 'All'}</td>
                <td className="px-4 py-3 text-gray-500">
                  {r.generatedBy ? `${r.generatedBy.firstName} ${r.generatedBy.lastName}` : '—'}
                </td>
                <td className="px-4 py-3 text-gray-500">{format(new Date(r.generatedAt), 'MMM d, yyyy HH:mm')}</td>
                <td className="px-4 py-3">
                  <button
                    onClick={() => handleDownload(r)}
                    className="flex items-center gap-1 text-xs font-medium text-growth-600 hover:text-growth-700 hover:underline transition-colors"
                  >
                    <Download size={12} /> Download
                  </button>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </div>
  );
}
